[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "development"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_FLAGS = "--no-audit --no-fund --include=dev"

[context.production]
  command = "npm config set registry https://registry.npmjs.org/ && npm ci --include=dev --no-audit --no-fund && npm run build"

[context.deploy-preview]
  command = "npm config set registry https://registry.npmjs.org/ && npm ci --include=dev --no-audit --no-fund && npm run build"
